version: '3.4'
services:
  vanilla-share:
    image: alfresco-share-vanilla:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../vanilla-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: vanilla-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  vanilla-acs:
    image: alfresco-content-services-vanilla:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../vanilla-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: "
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dmessaging.broker.url=\"failover:(nio://vanilla-activemq:61616)?timeout=3000&jms.useCompression=true\"
        "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - vanilla-acs-volume:/usr/local/tomcat/alf_data
      - ./exactTermSearch.properties:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/search/elasticsearch/config/exactTermSearch.properties
    depends_on:
      - vanilla-postgres
  vanilla-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - vanilla-db-volume:/var/lib/postgresql/data
  vanilla-activemq:
      image: alfresco/alfresco-activemq:5.16.1
      mem_limit: 1g
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP

  elasticsearch:
    image: opensearchproject/opensearch:1.3.14
    mem_limit: 1700m
    container_name: elasticsearch
    volumes:
      - opensearch-volume:/usr/share/opensearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
  live-indexing-metadata:
    image: quay.io/alfresco/alfresco-elasticsearch-live-indexing-metadata:4.0.0.1
    depends_on:
      - elasticsearch
      - vanilla-acs
    environment:
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      ELASTICSEARCH_INDEXNAME: alfresco
      SPRING_ACTIVEMQ_BROKERURL: nio://vanilla-activemq:61616

  live-indexing-mediation:
    image: quay.io/alfresco/alfresco-elasticsearch-live-indexing-mediation:4.0.0.1
    depends_on:
      - elasticsearch
      - vanilla-acs
    environment:
      JAVA_OPTS: "
        -Dalfresco.accepted-content-media-types-cache.enabled=false
        -Dalfresco.path-indexing-component.enabled=false
        -Dalfresco.content-indexing-component.enabled=false"
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      SPRING_ACTIVEMQ_BROKERURL: nio://vanilla-activemq:61616

volumes:
  vanilla-acs-volume:
    external: true
  vanilla-db-volume:
    external: true
  opensearch-volume:
    external: true
